logging:
  pattern:
    console: '%d{HH:mm:ss} %-5level %logger{36} - %msg%n'

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      exclude:
        - static/**
        - public/**
        - META-INF/**
